[package]
name = "e2p-sys"
version = "0.1.0"
authors = ["Michael Lass <bevan@bi-co.net>"]
edition = "2018"

[build-dependencies]
bindgen = "0.49.2"
metadeps = "1.1.2"

[package.metadata.pkg-config]
e2p = "*"

[dependencies]
